
name: 'Setup doko-js-cli'
description: 'Installs doko-js-cli from a specified repository and branch'

inputs:
  node-version:
    description: 'Node.js version to use'
    default: '22'
    required: false
  pnpm-version:
    description: 'pnpm version to use'
    default: '10'
    required: false
  rust-version:
    description: 'Rust toolchain version to use'
    default: 'stable'
  doko-repo:
    description: 'Repository URI of doko-js-cli'
    default: 'venture23-aleo/doko-js'
    required: false
  doko-branch:
    description: 'Branch of doko-js-cli to use'
    default: 'main'
    required: false

runs:
  using: "composite"
  steps:
  - name: Clone doko-js-cli branch
    uses: actions/checkout@v4
    with:
      repository: ${{ inputs.doko-repo }}
      ref: ${{ inputs.doko-branch }}
      path: doko-js-cli
      fetch-depth: 1

  - name: Setup pnpm
    uses: pnpm/action-setup@v4
    with:
      version: ${{ inputs.pnpm-version }}
      run_install: false

  - name: Setup Node.js for temporary repo
    uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}
      cache: 'pnpm'
      cache-dependency-path: 'doko-js-cli/pnpm-lock.yaml'

  - name: Install Rust and Cargo
    uses: dtolnay/rust-toolchain@master
    with:
      toolchain: ${{ inputs.rust-version }}

  - name: Cache Rust dependencies and build artifacts
    uses: Swatinem/rust-cache@v2
    with:
      working-directory: doko-js-cli/packages/wasm
      cache-directories: |
        "$HOME/.cargo/bin/wasm-pack"

  - name: Install wasm-pack
    shell: bash
    run: |
      echo "Installing wasm-pack..."
      cargo install wasm-pack
      
      # Add cargo bin to PATH and make sure it's available in current session
      echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      export PATH="$HOME/.cargo/bin:$PATH"
      
      # Verify installation
      which wasm-pack
      wasm-pack --version
  
  - name: Install and build doko-js-cli
    shell: bash
    working-directory: doko-js-cli
    run: |
      pnpm install
      pnpm run --r --filter "./packages/**" build
      npm run install:cli
      echo "doko-js-cli installed successfully ($(dokojs --version))"
